name: GitHub actions

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install gmp
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            echo "GMP not yet supported on $RUNNER_OS, won't build grid_synth"
          elif [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install -y libgmp-dev
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install gmp
          else
            echo "$RUNNER_OS not supported"
            exit 1
          fi

      - name: Configure staq
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build staq
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            export CPATH=$LIBRARY_PATH:/usr/local/include
            export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/lib
          fi
          cmake --build build

      - name: Install staq
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            cmake --build build --target install
          else
            sudo cmake --build build --target install
          fi

      - name: Build unit tests
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            export CPATH=$LIBRARY_PATH:/usr/local/include
            export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/lib
          fi
          cmake --build build --target unit_tests --parallel 4

      - name: Run unit tests
        run: ctest --test-dir build

      - name: Install pystaq
        run: pip3 install --user .
